updates

diff --git a/user_build b/user_build
--- a/user_build
+++ b/user_build
@@ -12,10 +12,6 @@ bazel="${install_dir}/bazel"
 
 if [[ ! -f "${bazel}" ]]; then
 
-    # Say that we are missing bazel, and will install it
-    echo "INFO: Required bazel version not found."
-    echo "downloading to ${bazel}..." >&2
-
     # Check for some bootstraping necessities
     command -v mkdir >/dev/null 2>&1 || { echo >&2 "I require mkdir but it's not installed.  Aborting."; exit 1; }
     command -v rm >/dev/null 2>&1 || { echo >&2 "I require rm but it's not installed.  Aborting."; exit 1; }
@@ -24,6 +20,10 @@ if [[ ! -f "${bazel}" ]]; then
     command -v tty >/dev/null 2>&1 || { echo >&2 "I require tty but it's not installed.  Aborting."; exit 1; }
     command -v wget >/dev/null 2>&1 || { echo >&2 "I require wget but it's not installed.  Aborting."; exit 1; }
     command -v sha256sum >/dev/null 2>&1 || { echo >&2 "I require sha256sum but it's not installed.  Aborting."; exit 1; }
+
+    # Say that we are missing bazel, and will install it
+    echo "INFO: Required bazel version not found."
+    echo "downloading to ${bazel}..." >&2
 
     # Setup install directory & delete it on failure
     mkdir -p "${install_dir}"
